services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mikrogeni-backend
    restart: unless-stopped
    network_mode: host
    working_dir: /data
    env_file:
      - .env
    environment:
      PORT: "1997"
    volumes:
      - backend_data:/data

  nginx:
    image: nginx:1.27-alpine
    container_name: mikrogeni-nginx
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  backend_data: